<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../HelloManager.wsdl"/>
      <rootElement name="criteria" namespace="http://www.example.org"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../HelloRulesService.wsdl"/>
      <rootElement name="callFunctionStateless" namespace="http://xmlns.oracle.com/HelloRules/HelloRulesService"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [MON DEC 16 22:01:00 EST 2013]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns1="http://www.example.org"
                xmlns:java="http://schemas.xmlsoap.org/wsdl/java/"
                xmlns:ns0="http://xmlns.oracle.com/bpel"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:tns="http://xmlns.oracle.com/HelloRules/HelloRulesService"
                xmlns:format="http://schemas.xmlsoap.org/wsdl/formatbinding/"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:rules="http://xmlns.oracle.com/bpel/rules"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:client="http://xmlns.oracle.com/HelloManagerApp/HelloManagerSoa/HelloManager"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns1 plnk wsdl xsd client java ns0 soap12 tns format soap rules xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <tns:callFunctionStateless>
      <tns:parameterList>
        <ns1:criteria>
          <ns1:MeTopSalary>
            <xsl:value-of select="/ns1:criteria/ns1:MeTopSalary"/>
          </ns1:MeTopSalary>
          <ns1:OtherTopSalary>
            <xsl:value-of select="/ns1:criteria/ns1:OtherTopSalary"/>
          </ns1:OtherTopSalary>
          <ns1:SameDepartment>
            <xsl:value-of select="/ns1:criteria/ns1:SameDepartment"/>
          </ns1:SameDepartment>
          <ns1:Manager>
            <xsl:value-of select="/ns1:criteria/ns1:Manager"/>
          </ns1:Manager>
          <ns1:DirectManager>
            <xsl:value-of select="/ns1:criteria/ns1:DirectManager"/>
          </ns1:DirectManager>
          <ns1:Subordinate>
            <xsl:value-of select="/ns1:criteria/ns1:Subordinate"/>
          </ns1:Subordinate>
          <ns1:HireDatePrior>
            <xsl:value-of select="/ns1:criteria/ns1:HireDatePrior"/>
          </ns1:HireDatePrior>
          <ns1:SalaryHiger>
            <xsl:value-of select="/ns1:criteria/ns1:SalaryHiger"/>
          </ns1:SalaryHiger>
        </ns1:criteria>
      </tns:parameterList>
    </tns:callFunctionStateless>
  </xsl:template>
</xsl:stylesheet>
